process.on('unhandledRejection', err => {
  throw err;
});

console.log('testing!!!');
